Added tty changes

diff --git a/config/docker/docker b/config/docker/docker
--- a/config/docker/docker
+++ b/config/docker/docker
@@ -42,11 +42,11 @@ dhp() {
 
 alias dps="docker ps -a"
 alias dpe='clear && docker ps -a -f "status=exited"'
-alias dpi='clear >$(tty) && echo -e "List of running containers" && docker ps --format "table {{.ID}}\t{{.RunningFor}}\t{{.Status}}\t{{.Image}}\t{{.Names}}"'
-alias dpp='clear >$(tty) && docker ps --format "table {{.ID}}\t{{.Names}}\t{{.Ports}}"'
-alias dpia='clear >$(tty) && docker ps --format "table {{.Names}}\t{{.ID}}\t{{.Status}}\t{{.Ports}}\t{{.Image}}\t{{.Command}}\{{.RunningFor}}\{{.Status}}"'
-alias dpsi='clear >$(tty) && docker ps --format "table {{.Names}}\t{{.Image}}\t{{.Ports}}"'
-alias dpsia='clear >$(tty) && docker ps -a --format "table {{.Names}}\t{{.Image}}\t{{.Ports}}"'
+alias dpi='clear  && echo -e "List of running containers" && docker ps --format "table {{.ID}}\t{{.RunningFor}}\t{{.Status}}\t{{.Image}}\t{{.Names}}"'
+alias dpp='clear  && docker ps --format "table {{.ID}}\t{{.Names}}\t{{.Ports}}"'
+alias dpia='clear  && docker ps --format "table {{.Names}}\t{{.ID}}\t{{.Status}}\t{{.Ports}}\t{{.Image}}\t{{.Command}}\{{.RunningFor}}\{{.Status}}"'
+alias dpsi='clear  && docker ps --format "table {{.Names}}\t{{.Image}}\t{{.Ports}}"'
+alias dpsia='clear  && docker ps -a --format "table {{.Names}}\t{{.Image}}\t{{.Ports}}"'
 alias dpl="docker pull $1"
 alias dis="docker images"
 alias drn="docker run -itd $1 $2"
@@ -153,7 +153,36 @@ pull_demo_images() {
 }
 
 
+docker_add_user_group() {
+  local user="${1:-$USER}"
 
+  # Must run as root or via sudo
+  if [[ $EUID -ne 0 ]]; then
+    echo "Please run with sudo:"
+    echo "  sudo docker_add_user_group <username>"
+    return 1
+  fi
+
+  # Check if user exists
+  if ! id "$user" &>/dev/null; then
+    echo "Error: User '$user' does not exist."
+    return 1
+  fi
+
+  # Create docker group if it doesn't exist
+  getent group docker >/dev/null || groupadd docker
+
+  # Add user to docker group
+  usermod -aG docker "$user"
+
+  echo "✓ User '$user' has been added to the docker group."
+  echo
+  echo "The user must log out and log back in (or run):"
+  echo "  newgrp docker"
+  echo
+  echo "Verify with:"
+  echo "  groups $user"
+}
 
 
 volume_export_import() {
